
import Foundation

enum Constants {
    static let apiCamera = "http://cars.cprogroup.ru/api/rubetek/cameras/"
    static let apiDoors = "http://cars.cprogroup.ru/api/rubetek/doors/"
    static let editingStar = "editingStar"
    static let star = "star"
    static let header = "Гостиная"
    static let lock = "lock"
    static let unlock = "unlock"
    static let rename = "rename"
    static let font = "Circe-Regular"
    static let fontTitle = "Circe-light"
    static let fonts = "SFProText-Light"
    static let identifire = "cell"
    static let rec = "rec"
    static let placeholder = "Enter new name"
    static let title = "Rename"
    static let titleCancel = "Cancel"
    static let save = "Save"
    static let main = "Main"
    static let secondViewController = "SeconViewController"
    static let titleNavigation = "Домофон общедомовой"
    static let shevron = "chevron.compact.up"
    static let arrow = "arrow.left"
    static let set = "Настройки"
    static let eye = "eye.slash"
    static let key = "key.fill"
    static let openDoor = "Открыть дверь"
}
